### ISSUE TITLE
Issue regarding internal background task

### ISSUE THREAD

**Issue by BlackKnight683** [finlaysawyer/discord-uptime#10]
```py
Unhandled exception in internal background task 'monitor_uptime'.
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/runner/AcademicPushyDivisor/cogs/monitor.py", line 68, in monitor_uptime
    for i in get_servers():
  File "/home/runner/AcademicPushyDivisor/utils/config.py", line 8, in get_servers
    return json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
  ```

**Comment by finlaysawyer** [comment]
Can you post the full error? I'm pretty sure there's some stuff missing here

**Comment by BlackKnight683** [comment]
this is the full error
i had an extra `,`
i fixed it :D

**Comment by finlaysawyer** [comment]
Ah I thought that might be the case. I'll add a friendlier error there in a future update, glad you got it working.
