### ISSUE TITLE
Uptime (just like downtime)

### ISSUE THREAD

**Issue by Aayush-683** [finlaysawyer/discord-uptime#7]
Like we can see downtime of website in the status command... how can we calculate the uptime of website?? is it possible? if yes then can you share code please :D

**Comment by finlaysawyer** [comment]
I haven't implemented uptime tracking or reporting yet, but this is definitely something to consider in the future :)

**Comment by Clashplayer-PROTECT** [comment]
Hello,
My FRIEND have got probleme with one error.
Preview error :
Traceback (most recent call last):
  File "bot.py", line 50, in <module>
    DiscordUptime().run(get_config("ODE3Njc0NDM0Nzg0NTI2MzM2.YEM8qA.TySp_dHpMjetKw27hS-VJaDPWJ4"))
  File "C:\Users\user\Desktop\discord-uptime-master\utils\config.py", line 31, in get_config
    raise Exception(f"Your config is out of date! Missing a value for {item}")
Exception: Your config is out of date! Missing a value for ODE3Njc0NDM0Nzg0NTI2MzM2.YEM8qA.BLLLALALALALALALAL-VJaDPWJ4

**Comment by finlaysawyer** [comment]
@Clashplayer-PROTECT You included your bot token, I've edited it out but I would reset it.

The token needs to go in the config file, e.g.

` "token": "TOKEN HERE",`

Rename `config.example.json` to `config.json` and edit the values.

**Comment by Clashplayer-PROTECT** [comment]
Thanks you
